import {
  GameActionLib,
  GameEventLib
} from "src/app/$mechanics";

import { move, crouch, stand, free, bandage, wait, pass } from "./action.configs";
import { climb, topple, mountSentry, triggerAlarm, rejuvenate, lootChest, placeCharacter, displaceCharacter } from "./interaction.configs";
import { wind } from "./event.configs";
import {
  deadlyBite, advancedDeadlyBite, swipe, advancedSwipe, block, shift, advancedCrushingBlow,
  advancedRockToss, crushingBlow, deflect, evade, rockToss, advancedChomp, advancedTendonRip,
  chomp, counter, rush, tendonRip, advancedEntangle, advancedGroundSmash, dodge, entangle,
  groundSmash, advancedDagger, advancedSword, avoid, dagger, elude, sword, advancedShieldSlam,
  advancedWarhammer, assault, shieldSlam, vanish, warhammer,
  advancedNeuroDart, advancedToxicBlow, neuroDart, sidestep, toxicBlow, advancedElectricNetgun,
  advancedGatlingGun, charge, electricNetgun, gatlingGun, advancedElectroBite, advancedRapidBite,
  electroBite, rapidBite, advancedPhotonGranade, advancedPhotonRifle, hide, photonGranade,
  photonRifle, advancedHealingNanobots, advancedPhotonShotgun, healingNanobots, photonShotgun,
  basicAvoid, basicHide, advancedPhotonBlaster, advancedPhotonCannon, photonBlaster, photonCannon,
  advancedBlastout, advancedNuclearPistol, blastout, nuclearPistol, advancedCharge, advancedNeuralInjection,
  advancedNuclearRifle, neuralInjection, nuclearRifle, shieldWall, advancedLifeDrain, advancedToxicFumes,
  basicAssault, lifeDrain, toxicFumes, advancedPropelledLunge, basicVanish, lightSabre, propelledLunge,
  advancedToxicBomb, advancedToxicSpit, toxicBomb, toxicSpit, advancedBleedingClaw, advancedToxicBite,
  bleedingClaw, toxicBite, advancedBite, advancedDominate, basicDodge, bite,
  dominate, advancedJumpOut, advancedToxicSpray, jumpOut, toxicSpray, advancedSuperBleedingClaw,
  advancedSuperDeadlyBite, superBleedingClaw, superDeadlyBite, battleChain, quickCharge,
  powerPunch, shockBaton, longBow, stunGun, advancedBlock, axe
} from "./ability.configs";


export const actions: GameActionLib = {
  // actions
  move,
  crouch,
  stand,
  free,
  bandage,
  wait,
  pass,

  // abilities
  deadlyBite,
  advancedDeadlyBite,
  swipe,
  advancedSwipe,
  block,
  shift,
  crushingBlow,
  advancedCrushingBlow,
  rockToss,
  advancedRockToss,
  evade,
  deflect,
  tendonRip,
  advancedTendonRip,
  chomp,
  advancedChomp,
  counter,
  rush,
  groundSmash,
  advancedGroundSmash,
  entangle,
  advancedEntangle,
  dodge,
  dagger,
  advancedDagger,
  sword,
  advancedSword,
  elude,
  avoid,
  warhammer,
  advancedWarhammer,
  shieldSlam,
  advancedShieldSlam,
  vanish,
  assault,
  toxicBlow,
  advancedToxicBlow,
  neuroDart,
  advancedNeuroDart,
  sidestep,
  gatlingGun,
  advancedGatlingGun,
  electricNetgun,
  advancedElectricNetgun,
  charge,
  electroBite,
  advancedElectroBite,
  rapidBite,
  advancedRapidBite,
  photonRifle,
  advancedPhotonRifle,
  photonGranade,
  advancedPhotonGranade,
  hide,
  photonShotgun,
  advancedPhotonShotgun,
  healingNanobots,
  advancedHealingNanobots,
  basicHide,
  basicAvoid,
  photonBlaster,
  advancedPhotonBlaster,
  photonCannon,
  advancedPhotonCannon,
  nuclearPistol,
  advancedNuclearPistol,
  blastout,
  advancedBlastout,
  nuclearRifle,
  advancedNuclearRifle,
  neuralInjection,
  advancedNeuralInjection,
  advancedCharge,
  shieldWall,
  toxicFumes,
  advancedToxicFumes,
  lifeDrain,
  advancedLifeDrain,
  basicAssault,
  lightSabre,
  propelledLunge,
  advancedPropelledLunge,
  basicVanish,
  toxicSpit,
  advancedToxicSpit,
  toxicBomb,
  advancedToxicBomb,
  toxicBite,
  advancedToxicBite,
  bleedingClaw,
  advancedBleedingClaw,
  bite,
  advancedBite,
  dominate,
  advancedDominate,
  basicDodge,
  toxicSpray,
  advancedToxicSpray,
  jumpOut,
  advancedJumpOut,
  superDeadlyBite,
  advancedSuperDeadlyBite,
  superBleedingClaw,
  advancedSuperBleedingClaw,
  battleChain,
  quickCharge,
  shockBaton,
  powerPunch,
  longBow,
  stunGun,
  axe,
  advancedBlock,

  // component interactions
  climb,
  topple,
  mountSentry,
  triggerAlarm,
  rejuvenate,
  lootChest,

  // character interactions

  // special interactions
  placeCharacter,
  displaceCharacter,
};

export const events: GameEventLib = {
  wind,
};
